package com.davina.user.dao;

import com.davina.user.pojo.FollowExample;
import com.davina.user.pojo.FollowKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface FollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated
     */
    int countByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated
     */
    int deleteByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FollowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated
     */
    int insert(FollowKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated
     */
    int insertSelective(FollowKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated
     */
    List<FollowKey> selectByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FollowKey record, @Param("example") FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FollowKey record, @Param("example") FollowExample example);
}