server:
  port: 9010
spring:
  application:
    name: friend-model
  dataSource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: root
  rabbitmq:
    host: 127.0.0.1

mybatis:
  type-aliases-package: com.davina.friend.pojo
  mapper-locations: classpath:/com/davina/friend/dao/*.xml

logging:
  level:
    com.davina.friend: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
zuul:
  host:
    socket-timeout-millis: 12000
    connect-timeout-millis: 12000
  routes:
    base-model:
      path: /base/**
      serviceId: base-model
    recruit-model:
      path: /recruit/**
      serviceId: recruit-model
    qa-model:
      path: /qa/**
      serviceId: qa-model
    article-model:
      path: /article/**
      serviceId: article-model
    gathering-model:
      path: /gathering/**
      serviceId: gathering-model
    spit-model:
      path: /spit/**
      serviceId: spit-model
    search-model:
      path: /search/**
      serviceId: search-model
    user-model:
      path: /user/**
      serviceId: user-model
jwt:
  config:
    key: davian
    ttl: 360000
