server:
  port: 9005
spring:
  application:
    name: gathering-model
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_gathering?characterEncoding=utf-8
    username: root
    password: root
  rabbitmq:
    host: 127.0.0.1

mybatis:
  type-aliases-package: com.davina.gathering.pojo
  mapper-locations: classpath:/com/davina/gathering/dao/*.xml

logging:
  level:
    com.davina.gathering: debug

eureka:
    client:
      service-url:
        defaultZone: http://localhost:6868/eureka
    instance:
      prefer-ip-address: true

zuul:
  routes:
    base-model:
      path: /base/**
      serviceId: base-model
    recruit-model:
      path: /recruit/**
      serviceId: recruit-model
    qa-model:
      path: /qa/**
      serviceId: qa-model
    article-model:
      path: /article/**
      serviceId: article-model
    spit-model:
      path: /spit/**
      serviceId: spit-model
    search_model:
      path: /search/**
      serviceId: search_model
    user-model:
      path: /user/**
      serviceId: user-model
    friend-model:
      path: /friend/**
      serviceId: friend-model



