package com.davina.gathering.pojo;

import java.util.Date;

public class GatheringWithBLOBs extends Gathering {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.detail
     *
     * @mbggenerated
     */
    private String detail;

    public GatheringWithBLOBs(String id, String name, String sponsor, String image, Date starttime, Date endtime, String address, Date enrolltime, String state, String city, String summary, String detail) {
        super(id, name, sponsor, image, starttime, endtime, address, enrolltime, state, city);
        this.summary = summary;
        this.detail = detail;
    }

    public GatheringWithBLOBs() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.summary
     *
     * @return the value of tb_gathering.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.summary
     *
     * @param summary the value for tb_gathering.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.detail
     *
     * @return the value of tb_gathering.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.detail
     *
     * @param detail the value for tb_gathering.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}