package com.davina.gathering.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

@Table(name = "tb_gathering")
public class Gathering implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.id
     *
     * @mbggenerated
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.sponsor
     *
     * @mbggenerated
     */
    private String sponsor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.starttime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "GMT+8")
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.endtime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "GMT+8")
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.enrolltime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "GMT+8")
    private Date enrolltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gathering.city
     *
     * @mbggenerated
     */
    private String city;

    public Gathering(String id, String name, String sponsor, String image, Date starttime, Date endtime, String address, Date enrolltime, String state, String city) {
        this.id = id;
        this.name = name;
        this.sponsor = sponsor;
        this.image = image;
        this.starttime = starttime;
        this.endtime = endtime;
        this.address = address;
        this.enrolltime = enrolltime;
        this.state = state;
        this.city = city;
    }

    public Gathering() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.id
     *
     * @return the value of tb_gathering.id
     *
     * @mbggenerated
     */

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.id
     *
     * @param id the value for tb_gathering.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.name
     *
     * @return the value of tb_gathering.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.name
     *
     * @param name the value for tb_gathering.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.sponsor
     *
     * @return the value of tb_gathering.sponsor
     *
     * @mbggenerated
     */
    public String getSponsor() {
        return sponsor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.sponsor
     *
     * @param sponsor the value for tb_gathering.sponsor
     *
     * @mbggenerated
     */
    public void setSponsor(String sponsor) {
        this.sponsor = sponsor == null ? null : sponsor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.image
     *
     * @return the value of tb_gathering.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.image
     *
     * @param image the value for tb_gathering.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.starttime
     *
     * @return the value of tb_gathering.starttime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.starttime
     *
     * @param starttime the value for tb_gathering.starttime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.endtime
     *
     * @return the value of tb_gathering.endtime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.endtime
     *
     * @param endtime the value for tb_gathering.endtime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.address
     *
     * @return the value of tb_gathering.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.address
     *
     * @param address the value for tb_gathering.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.enrolltime
     *
     * @return the value of tb_gathering.enrolltime
     *
     * @mbggenerated
     */
    public Date getEnrolltime() {
        return enrolltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.enrolltime
     *
     * @param enrolltime the value for tb_gathering.enrolltime
     *
     * @mbggenerated
     */
    public void setEnrolltime(Date enrolltime) {
        this.enrolltime = enrolltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.state
     *
     * @return the value of tb_gathering.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.state
     *
     * @param state the value for tb_gathering.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gathering.city
     *
     * @return the value of tb_gathering.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gathering.city
     *
     * @param city the value for tb_gathering.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}