package com.davina.gathering.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsergathExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public UsergathExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userid like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userid not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andGathidIsNull() {
            addCriterion("gathid is null");
            return (Criteria) this;
        }

        public Criteria andGathidIsNotNull() {
            addCriterion("gathid is not null");
            return (Criteria) this;
        }

        public Criteria andGathidEqualTo(String value) {
            addCriterion("gathid =", value, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidNotEqualTo(String value) {
            addCriterion("gathid <>", value, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidGreaterThan(String value) {
            addCriterion("gathid >", value, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidGreaterThanOrEqualTo(String value) {
            addCriterion("gathid >=", value, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidLessThan(String value) {
            addCriterion("gathid <", value, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidLessThanOrEqualTo(String value) {
            addCriterion("gathid <=", value, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidLike(String value) {
            addCriterion("gathid like", value, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidNotLike(String value) {
            addCriterion("gathid not like", value, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidIn(List<String> values) {
            addCriterion("gathid in", values, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidNotIn(List<String> values) {
            addCriterion("gathid not in", values, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidBetween(String value1, String value2) {
            addCriterion("gathid between", value1, value2, "gathid");
            return (Criteria) this;
        }

        public Criteria andGathidNotBetween(String value1, String value2) {
            addCriterion("gathid not between", value1, value2, "gathid");
            return (Criteria) this;
        }

        public Criteria andExetimeIsNull() {
            addCriterion("exetime is null");
            return (Criteria) this;
        }

        public Criteria andExetimeIsNotNull() {
            addCriterion("exetime is not null");
            return (Criteria) this;
        }

        public Criteria andExetimeEqualTo(Date value) {
            addCriterion("exetime =", value, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeNotEqualTo(Date value) {
            addCriterion("exetime <>", value, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeGreaterThan(Date value) {
            addCriterion("exetime >", value, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("exetime >=", value, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeLessThan(Date value) {
            addCriterion("exetime <", value, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeLessThanOrEqualTo(Date value) {
            addCriterion("exetime <=", value, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeIn(List<Date> values) {
            addCriterion("exetime in", values, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeNotIn(List<Date> values) {
            addCriterion("exetime not in", values, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeBetween(Date value1, Date value2) {
            addCriterion("exetime between", value1, value2, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeNotBetween(Date value1, Date value2) {
            addCriterion("exetime not between", value1, value2, "exetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_usergath
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}