package com.davina.gathering.pojo;

import java.io.Serializable;

public class UsergathKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usergath.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usergath.gathid
     *
     * @mbggenerated
     */
    private String gathid;

    public UsergathKey(String userid, String gathid) {
        this.userid = userid;
        this.gathid = gathid;
    }

    public UsergathKey() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usergath.userid
     *
     * @return the value of tb_usergath.userid
     *
     * @mbggenerated
     */

    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usergath.userid
     *
     * @param userid the value for tb_usergath.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usergath.gathid
     *
     * @return the value of tb_usergath.gathid
     *
     * @mbggenerated
     */
    public String getGathid() {
        return gathid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usergath.gathid
     *
     * @param gathid the value for tb_usergath.gathid
     *
     * @mbggenerated
     */
    public void setGathid(String gathid) {
        this.gathid = gathid == null ? null : gathid.trim();
    }
}