package com.davina.article.pojo;

import io.swagger.annotations.ApiModel;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

@ApiModel
@Table(name = "tb_article")
public class Article implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.id
     *
     * @mbggenerated
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.columnid
     *
     * @mbggenerated
     */
    private String columnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ispublic
     *
     * @mbggenerated
     */
    private String ispublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.istop
     *
     * @mbggenerated
     */
    private String istop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.visits
     *
     * @mbggenerated
     */
    private Integer visits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.thumbup
     *
     * @mbggenerated
     */
    private Integer thumbup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.comment
     *
     * @mbggenerated
     */
    private Integer comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.channelid
     *
     * @mbggenerated
     */
    private String channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.content
     *
     * @mbggenerated
     */
    private String content;

    public Article() {
    }

    public Article(String id, String columnid, String userid, String title, String image, Date createtime, Date updatetime, String ispublic, String istop, Integer visits, Integer thumbup, Integer comment, String state, String channelid, String url, String type, String content) {
        this.id = id;
        this.columnid = columnid;
        this.userid = userid;
        this.title = title;
        this.image = image;
        this.createtime = createtime;
        this.updatetime = updatetime;
        this.ispublic = ispublic;
        this.istop = istop;
        this.visits = visits;
        this.thumbup = thumbup;
        this.comment = comment;
        this.state = state;
        this.channelid = channelid;
        this.url = url;
        this.type = type;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.id
     *
     * @return the value of tb_article.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.id
     *
     * @param id the value for tb_article.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.columnid
     *
     * @return the value of tb_article.columnid
     *
     * @mbggenerated
     */
    public String getColumnid() {
        return columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.columnid
     *
     * @param columnid the value for tb_article.columnid
     *
     * @mbggenerated
     */
    public void setColumnid(String columnid) {
        this.columnid = columnid == null ? null : columnid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.userid
     *
     * @return the value of tb_article.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.userid
     *
     * @param userid the value for tb_article.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.title
     *
     * @return the value of tb_article.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.title
     *
     * @param title the value for tb_article.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.image
     *
     * @return the value of tb_article.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.image
     *
     * @param image the value for tb_article.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.createtime
     *
     * @return the value of tb_article.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.createtime
     *
     * @param createtime the value for tb_article.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.updatetime
     *
     * @return the value of tb_article.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.updatetime
     *
     * @param updatetime the value for tb_article.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ispublic
     *
     * @return the value of tb_article.ispublic
     *
     * @mbggenerated
     */
    public String getIspublic() {
        return ispublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ispublic
     *
     * @param ispublic the value for tb_article.ispublic
     *
     * @mbggenerated
     */
    public void setIspublic(String ispublic) {
        this.ispublic = ispublic == null ? null : ispublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.istop
     *
     * @return the value of tb_article.istop
     *
     * @mbggenerated
     */
    public String getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.istop
     *
     * @param istop the value for tb_article.istop
     *
     * @mbggenerated
     */
    public void setIstop(String istop) {
        this.istop = istop == null ? null : istop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.visits
     *
     * @return the value of tb_article.visits
     *
     * @mbggenerated
     */
    public Integer getVisits() {
        return visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.visits
     *
     * @param visits the value for tb_article.visits
     *
     * @mbggenerated
     */
    public void setVisits(Integer visits) {
        this.visits = visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.thumbup
     *
     * @return the value of tb_article.thumbup
     *
     * @mbggenerated
     */
    public Integer getThumbup() {
        return thumbup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.thumbup
     *
     * @param thumbup the value for tb_article.thumbup
     *
     * @mbggenerated
     */
    public void setThumbup(Integer thumbup) {
        this.thumbup = thumbup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.comment
     *
     * @return the value of tb_article.comment
     *
     * @mbggenerated
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.comment
     *
     * @param comment the value for tb_article.comment
     *
     * @mbggenerated
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.state
     *
     * @return the value of tb_article.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.state
     *
     * @param state the value for tb_article.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.channelid
     *
     * @return the value of tb_article.channelid
     *
     * @mbggenerated
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.channelid
     *
     * @param channelid the value for tb_article.channelid
     *
     * @mbggenerated
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.url
     *
     * @return the value of tb_article.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.url
     *
     * @param url the value for tb_article.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.type
     *
     * @return the value of tb_article.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.type
     *
     * @param type the value for tb_article.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.content
     *
     * @return the value of tb_article.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.content
     *
     * @param content the value for tb_article.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}