package com.davina.article.pojo;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;


@Table(name = "tb_user_thumup")
public class UserThumbup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_thumup.user_id
     *
     * @mbggenerated
     */
    @Id
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_thumup.article_id
     *
     * @mbggenerated
     */
    @Id
    private String articleId;

    public UserThumbup(String userId, String articleId) {
        this.userId = userId;
        this.articleId = articleId;
    }

    public UserThumbup() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_thumup.user_id
     *
     * @return the value of tb_user_thumup.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_thumup.user_id
     *
     * @param userId the value for tb_user_thumup.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_thumup.article_id
     *
     * @return the value of tb_user_thumup.article_id
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_thumup.article_id
     *
     * @param articleId the value for tb_user_thumup.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }
}