server:
  port: 12000
spring:
  application:
    name: config-model
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HahAmypage/springcloudpro.git/config_model/src/main/resources/
