package com.davina.friend.dao;

import com.davina.friend.pojo.NoFriendExample;
import com.davina.friend.pojo.NoFriend;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface NoFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_nofriend
     *
     * @mbggenerated
     */
    int countByExample(NoFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_nofriend
     *
     * @mbggenerated
     */
    int deleteByExample(NoFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_nofriend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(NoFriend key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_nofriend
     *
     * @mbggenerated
     */
    int insert(NoFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_nofriend
     *
     * @mbggenerated
     */
    int insertSelective(NoFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_nofriend
     *
     * @mbggenerated
     */
    List<NoFriend> selectByExample(NoFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_nofriend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoFriend record, @Param("example") NoFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_nofriend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoFriend record, @Param("example") NoFriendExample example);
}