package com.davina.friend.pojo;

import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "tb_friend")
@IdClass(Friend.class)
public class Friend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.userid
     *
     * @mbggenerated
     */
    @Id
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.friendid
     *
     * @mbggenerated
     */
    @Id
    private String friendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.islike
     *
     * @mbggenerated
     */
    private String islike;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.userid
     *
     * @return the value of tb_friend.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.userid
     *
     * @param userid the value for tb_friend.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.friendid
     *
     * @return the value of tb_friend.friendid
     *
     * @mbggenerated
     */
    public String getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.friendid
     *
     * @param friendid the value for tb_friend.friendid
     *
     * @mbggenerated
     */
    public void setFriendid(String friendid) {
        this.friendid = friendid == null ? null : friendid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.islike
     *
     * @return the value of tb_friend.islike
     *
     * @mbggenerated
     */
    public String getIslike() {
        return islike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.islike
     *
     * @param islike the value for tb_friend.islike
     *
     * @mbggenerated
     */
    public void setIslike(String islike) {
        this.islike = islike == null ? null : islike.trim();
    }
}