package com.davina.friend.pojo;

import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "tb_nofriend")
@IdClass(NoFriend.class)
public class NoFriend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_nofriend.userid
     *
     * @mbggenerated
     */
    @Id
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_nofriend.friendid
     *
     * @mbggenerated
     */
    @Id
    private String friendid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_nofriend.userid
     *
     * @return the value of tb_nofriend.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_nofriend.userid
     *
     * @param userid the value for tb_nofriend.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_nofriend.friendid
     *
     * @return the value of tb_nofriend.friendid
     *
     * @mbggenerated
     */
    public String getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_nofriend.friendid
     *
     * @param friendid the value for tb_nofriend.friendid
     *
     * @mbggenerated
     */
    public void setFriendid(String friendid) {
        this.friendid = friendid == null ? null : friendid.trim();
    }
}