package com.davina.gathering.dao;

import com.davina.gathering.pojo.Gathering;
import com.davina.gathering.pojo.GatheringExample;
import com.davina.gathering.pojo.GatheringWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GatheringMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int countByExample(GatheringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int deleteByExample(GatheringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int insert(GatheringWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int insertSelective(GatheringWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    List<GatheringWithBLOBs> selectByExampleWithBLOBs(GatheringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    List<Gathering> selectByExample(GatheringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    GatheringWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GatheringWithBLOBs record, @Param("example") GatheringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") GatheringWithBLOBs record, @Param("example") GatheringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Gathering record, @Param("example") GatheringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GatheringWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(GatheringWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gathering
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Gathering record);
}