package com.davina.gathering.dao;

import com.davina.gathering.pojo.Usergath;
import com.davina.gathering.pojo.UsergathExample;
import com.davina.gathering.pojo.UsergathKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface UsergathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int countByExample(UsergathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int deleteByExample(UsergathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UsergathKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int insert(Usergath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int insertSelective(Usergath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    List<Usergath> selectByExample(UsergathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    Usergath selectByPrimaryKey(UsergathKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Usergath record, @Param("example") UsergathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Usergath record, @Param("example") UsergathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Usergath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_usergath
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Usergath record);
}