server:
  port: 9003
spring:
  application:
    name: qa-model
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_qa?characterEncoding=utf-8
    username: root
    password: root

mybatis:
  type-aliases-package: com.davina.qa.pojo
  mapper-locations: classpath:/com/davina/qa/dao/*.xml

logging:
  level:
    com.davina.qa: debug


eureka:
    client:
      service-url:
        defaultZone: http://localhost:6868/eureka
    instance:
      prefer-ip-address: true

zuul:
  routes:
    base-model:
      path: /base/**
      serviceId: base-model
    recruit-model:
      path: /recruit/**
      serviceId: recruit-model
    article-model:
      path: /article/**
      serviceId: article-model
    gathering-model:
      path: /gathering/**
      serviceId: gathering-model
    spit-model:
      path: /spit/**
      serviceId: spit-model


