package com.davina.user.pojo;

import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "tb_follow")
public class FollowKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow.targetuser
     *
     * @mbggenerated
     */
    private String targetuser;

    public FollowKey() {
    }

    public FollowKey(String userid, String targetuser) {
        this.userid = userid;
        this.targetuser = targetuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow.userid
     *
     * @return the value of tb_follow.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow.userid
     *
     * @param userid the value for tb_follow.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow.targetuser
     *
     * @return the value of tb_follow.targetuser
     *
     * @mbggenerated
     */
    public String getTargetuser() {
        return targetuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow.targetuser
     *
     * @param targetuser the value for tb_follow.targetuser
     *
     * @mbggenerated
     */
    public void setTargetuser(String targetuser) {
        this.targetuser = targetuser == null ? null : targetuser.trim();
    }
}