package com.davina.article.dao;

import com.davina.article.pojo.Column;
import com.davina.article.pojo.ColumnExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int countByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int deleteByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int insert(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int insertSelective(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    List<Column> selectByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    Column selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Column record, @Param("example") ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Column record, @Param("example") ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Column record);
}