package com.davina.article.dao;

import com.davina.article.pojo.UserThumbupExample;
import com.davina.article.pojo.UserThumbup;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface UserThumbupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_thumup
     *
     * @mbggenerated
     */
    int countByExample(UserThumbupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_thumup
     *
     * @mbggenerated
     */
    int deleteByExample(UserThumbupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_thumup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserThumbup key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_thumup
     *
     * @mbggenerated
     */
    int insert(UserThumbup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_thumup
     *
     * @mbggenerated
     */
    int insertSelective(UserThumbup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_thumup
     *
     * @mbggenerated
     */
    List<UserThumbup> selectByExample(UserThumbupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_thumup
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserThumbup record, @Param("example") UserThumbupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_thumup
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserThumbup record, @Param("example") UserThumbupExample example);
}